version: '3.9'

services:

  postgres-db:
    image: postgres:16-alpine3.18
    container_name: postgres-db 
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - env/development.env
    volumes:
      - ../postgres:/var/lib/postgresql/data

    
  redis-db:
    image: redis:7
    container_name: redis-db
    ports:
      - "6379:6379"
    volumes:
      - ../redis:/var/lib/redis/data 

#    environment:
#      POSTGRES_DB: ${POSTGRES_DB}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_USER : ${POSTGRES_USER}