name: Run tests on push to develop

on:
  push:
    branches: [ "feature/user" ]
  pull_request:
    branches: [ "feature/user" ]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
